


include misc/3ds/3ds.profile.mk

include misc/3ds/build-cia.mk
include misc/3ds/build-elf.mk
include misc/3ds/build-smdh.mk
include misc/3ds/build-3dsx.mk
include misc/3ds/build-makerom.mk

