name: Build latest (Linux)

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-linux
  cancel-in-progress: true

jobs:
#============================================
# =============== 32 BIT LINUX ==============
# ===========================================
  build-32:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        shell: bash
        run: |
          echo -n 'APT::Install-Suggests "false";' | sudo tee /etc/apt/apt.conf.d/99-no_recommends
          sudo dpkg --add-architecture i386
          sudo apt-get -y update
          sudo apt-get -y install \
              clang \
              libc6-dev-i386 \
              libx11-dev:i386 libxi-dev:i386 \
              libglvnd-dev:i386 libgl-dev:i386 \
              x11proto-core-dev \
              x11proto-input-dev \
              x11proto-kb-dev
              

      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Compile 32 bit Linux build (OpenGL 1)
        shell: bash
        run: |
          # Enable support for i386
          export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig
          unset PKG_CONFIG_LIBDIR
          
          export CFLAGS="-m32"
          export LDFLAGS="-m32"
          export COLOR="off"

          cat >> config.mk << 'EOF'
          
          CFLAGS += $(shell pkg-config --cflags x11 gl xi) -DCC_COMMIT_SHA="${GITHUB_SHA::9}"
          CFLAGS += -O2 -s -fno-stack-protector -Werror -fvisibility=hidden -rdynamic -Werror
          CFLAGS += -fcf-protection=none -Wl,--unresolved-symbols=ignore-in-shared-libs
          LIBS   += $(shell pkg-config --libs x11 gl xi) -lm -ldl -lpthread

          EOF
          
          make -fNewMakefile.mk target=cc-nix32-gl1 platform=linux-gl1
          make -fNewMakefile.mk target=cc-nix32-gl2 platform=linux-gl2 EXTRA_CFLAGS="-DCC_GFX_BACKEND=CC_GFX_BACKEND_GL2"
      
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-nix32-gl1'
          DEST_NAME: 'ClassiCube-Linux32-OpenGL'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-nix32-gl2'
          DEST_NAME: 'ClassiCube-Linux32-ModernGL'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'linux32'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce 32 bit Linux build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'

#============================================
# =============== 64 BIT LINUX ==============
# ===========================================
  build-64:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Install packages
        shell: bash
        run: |
          echo -n 'APT::Install-Suggests "false";' | sudo tee /etc/apt/apt.conf.d/99-no_recommends
          sudo apt-get -y update
          sudo apt-get -y install \
              clang \
              libc6-dev \
              libx11-dev libxi-dev \
              libgl-dev libglvnd-dev

      - name: Compile 64 bit Linux builds
        shell: bash
        env:
          LIBS: "$(pkg-config --libs x11 gl xi) -lm -ldl -lpthread"
          SRCS: "src/*.c third_party/bearssl/*.c" 
          FLAGS: "$(pkg-config --cflags x11 gl xi) -O1 -pipe -s -fno-stack-protector -fno-math-errno -Werror -fvisibility=hidden -rdynamic"
          NIX64_FLAGS:  "-no-pie -fno-pie -m64 -fcf-protection=none -rdynamic -Wl,--unresolved-symbols=ignore-in-shared-libs"
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\"${GITHUB_SHA::9}\"
         
          clang ${{ env.SRCS }} ${{ env.FLAGS }} ${{ env.NIX64_FLAGS }} $LATEST_FLAG -o cc-nix64-gl1 ${{ env.LIBS }}
          clang ${{ env.SRCS }} ${{ env.FLAGS }} ${{ env.NIX64_FLAGS }} $LATEST_FLAG -DCC_GFX_BACKEND=CC_GFX_BACKEND_GL2 -o cc-nix64-gl2 ${{ env.LIBS }}
          #clang ${{ env.SRCS }} ${{ env.FLAGS }} ${{ env.NIX64_FLAGS }} $LATEST_FLAG -DCC_GFX_BACKEND=CC_GFX_BACKEND_GL2 -DCC_WIN_BACKEND=CC_WIN_BACKEND_SDL2 -o cc-sdl64-gl2 -lSDL2  ${{ env.LIBS }}
          
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-nix64-gl1'
          DEST_NAME: 'ClassiCube-Linux64-OpenGL'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-nix64-gl2'
          DEST_NAME: 'ClassiCube-Linux64-ModernGL'
          
#      - uses: ./.github/actions/upload_build
#        with:
#          SOURCE_FILE: 'cc-sdl64-gl2'
#          DEST_NAME: 'ClassiCube-Linux64-SDL2'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'linux64'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce 64 bit Linux build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
