name: Build latest (Mac Classic)

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-mac-classic
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/autc04/retro68
    steps:
      - uses: actions/checkout@v5
      - name: Compile Mac classic build
        run: |
          export RETRO68=/Retro68-build/toolchain
          export MAKEFLAGS="$MAKEFLAGS -j$(nproc)"
          make macclassic_ppc
          make macclassic_68k
          make macclassic_68k ARCH_68040=1


      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-ppc.dsk'
          DEST_NAME: 'ClassiCube-ppc.dsk'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-68k.dsk'
          DEST_NAME: 'ClassiCube-68k.dsk'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-68040.dsk'
          DEST_NAME: 'ClassiCube-68040.dsk'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'macclassic'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce Mac Classic build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
