name: Build latest (3DS)
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-3ds
  cancel-in-progress: true

jobs:
  build-3DS:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v5
      - name: Compile 3DS build
        run: |
          # Optimization for leveraging multicore
          export MAKEFLAGS="$MAKEFLAGS -j$(nproc)"

          # DEVKITPRO Toolchain
          export CC="$DEVKITPRO/devkitARM/bin/arm-none-eabi-gcc"
          export LD="$CC"

          # Miscellaneous tools provided by devkitpro
          export DSXTOOL  = "$DEVKITPRO/tools/bin/3dsxtool"
          export SMDHTOOL = "$DEVKITPRO/tools/bin/smdhtool
          export PICASSO  = "$DEVKITPRO/tools/bin/picasso
          export BIN2S    = "$DEVKITPRO/tools/bin/bin2s

          echo include misc/3ds/3ds.profile.mk >> config.mk
          make -fNewMakefile.mk

      - name: Display compiler info
        run: |
          make -fNewMakefile.mk CC=$DEVKITPRO/devkitARM/bin/arm-none-eabi-gcc platform=3ds compiler-info

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-3ds.cia'
          DEST_NAME: 'ClassiCube-3ds.cia'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-3ds.3dsx'
          DEST_NAME: 'ClassiCube-3ds.3dsx'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-3ds.elf'
          DEST_NAME: 'ClassiCube-3ds.elf'

      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: '3ds'

      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce 3DS build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
