on: [workflow_call]

jobs:
  build:
    timeout-minutes: 7
    name: Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    environment: Canary

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: i386
            cflags: -m32 -march=i386 -mtune=bonnell --target=i386-linux-gnu
            output: OpenCraft-i386

          - arch: x86_64
            cflags: -m64 -march=x86-64 -mtune=bonnell --target=x86_64-linux-gnu
            output: OpenCraft-x86_64v1

    steps:
      - name: Fetch OpenCraft source code
        uses: actions/checkout@v7
        with:
          submodules: recursive
      
      - name: Setup LLVM toolchain
        uses: ./.github/actions/llvm-toolchain
        with:
          architecture: ${{ matrix.arch }}
          cflags: ${{ matrix.cflags }}

      - name: Compile
        run: |
          make TARGET="${{ matrix.output }}" \
            COMMON_FLAGS="-Weverything -Wno-unsafe-buffer-usage -O2"

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
